;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        anzu-replace-at-cursor-thing
        helm-M-x
        hippie-expand-no-case-fold
        hungry-delete-backward
        hungry-delete-forward
        isearch-abort
        isearch-forward-regexp
        isearch-printing-char
        iy-go-to-char--command
        kao/move-beginning-of-line
        kill-region
        markdown-cycle
        markdown-outdent-or-delete
        org-cycle
        org-delete-char
        org-meta-return
        org-metaleft
        org-metaright
        org-self-insert-command
        org-todo
        sp--self-insert-command
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-kill-sexp
        sp-kill-word
        sp-splice-sexp
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        helm-confirm-and-exit-minibuffer
        highlight-symbol-next
        magit-goto-next-section
        wgrep-finish-edit
        ))
