;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        hungry-delete-backward
        hungry-delete-forward
        kill-region
        org-metaleft
        org-metaright
        org-self-insert-command
        sp--self-insert-command
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        helm-confirm-and-exit-minibuffer
        magit-goto-next-section
        ))
