(source melpa)

(depends-on "ag")
(depends-on "browse-kill-ring")
(depends-on "exec-path-from-shell")
(depends-on "flx-ido")
(depends-on "ido-ubiquitous")
(depends-on "magit")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "smartparens")
(depends-on "smex")
