(source melpa)

(depends-on "ace-jump-mode")
(depends-on "ag")
(depends-on "browse-kill-ring")
(depends-on "elisp-slime-nav")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "flx-ido")
(depends-on "ido-ubiquitous")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "paradox")
(depends-on "projectile")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "undo-tree")