;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from defaults.el

(register-definition-prefixes "defaults" '("yes-or-no-p"))


;;; Generated autoloads from defuns.el

(register-definition-prefixes "defuns" '("copy-file-name-" "default-font-size" "delete-current-buffer-file" "insert-iso-timestamp" "kao/" "large-font-size" "move-current-buffer-file" "rename-current-buffer-file"))


;;; Generated autoloads from emoji.el

(register-definition-prefixes "emoji" '("--set-emoji-font"))


;;; Generated autoloads from setup-hippie.el

(register-definition-prefixes "setup-hippie" '("he-search-loc-" "hippie-expand-no-case-fold" "try-expand-"))


;;; Generated autoloads from setup-js.el

(register-definition-prefixes "setup-js" '("kao/ts-eglot-organize-imports"))


;;; Generated autoloads from setup-magit.el

(register-definition-prefixes "setup-magit" '("kao/magit-ediff-dwim"))


;;; Generated autoloads from setup-theme.el

(register-definition-prefixes "setup-theme" '("general-theme-config"))


;;; Generated autoloads from setup-treemacs.el

(register-definition-prefixes "setup-treemacs" '("kao/treemacs-close"))

;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
